### PR TITLE
bug-34 :: Fix coin name overflow in coin detail header

### LINKED ISSUE #34: Fix long coin name over flow.
Seen in coin list screen item. But similar behaviour should be seen in coins details screen header and home screen owned coin item. Therefore address all.

### PR DESCRIPTION
**Pull request by drahovac**
Suggestion to fix https://github.com/RyanKoech/android-krypto/issues/34

It is maybe overkill to use Layout for measurement, but I wanted to add min width for name part, so even if balance part was too long (small display, big font, large amount), the view would not overflow. If we do not care for edge case, that amount part is too long for the screen, just weight modifier can be used.

### CODE REVIEW

**Comment by drahovac** [comment]
Overflow name
Screenshot_1689247677

Normal state
Screenshot_1689247684

Overflow balance 
Screenshot_1689247744

**Comment by RyanKoech** [comment]
What I had in mind concerning this was:
- Basic Fix: Using ellipses. Specifically for the name. The price will always have weight of 1 since anything value at that very high amount is an extreme edge case. (Trillions of dollars for a coin? 🤣)
- Cool Fix : Having the name get cut off but its animates horizontally to show the whole name

Ultimately we don't need to worry about an insanely large price.

**Comment by drahovac** [comment]
Higher version of Compose has a modifier called "basicMarquee" that animates text horizontally. I needed to update the Compose version (as well as some other versions for compatibility). The issue has been fixed in "coin_detail" and "coin_list."

**Comment by drahovac** [comment]
Screenshot_1689268983
Screenshot_1689268986
Screenshot_1689268989

**Comment by RyanKoech** [comment]
Awesome! Looks all good!

**Comment by RyanKoech** [comment]
One more thing. You can bump the `versionPatch` in `dependencies.gradle` up by one then it'll be all good to merge.

**Pull request merged**
