### PR TITLE
Bug-89 :: Crash in coin details screen 

### LINKED ISSUE #89: Bug: Crash in coin details screen
Steps to reproduce:
- Open app (Release variant) not observed in debug but stand to be corrected
- Go to coin list screen
- Search world coin
- Click world coin to go to its coin details screen
- select any other time range on the graph but 30 days
- finally select 30 days
- **Observed:** App crashes **Expected:** Show changes over 30 days

**Leads**
This potentially has to do with the way 90 days as fetch from the API is trimed down to 30 days and since the world coin hasn't been around for 30 days it causes the logic to break.

### LINKED ISSUE #90: Bug : Release Crash on Failed network request
Steps to repsoduce:
- Open app ( Release variant)
- Cause a network failure either by turn off internet connection or click multiple coins in coin list screen to exhaust the coin gecko 1 minute limit. 
- **Observed** App crashes in coinlistscreen, coindetailsscreen and choose coinlistscreen (when it tried to fetch remote of the local is empty)

### PR DESCRIPTION
**Pull request by RyanKoech**
Replace try catch with if else.
Interestingly the try catch blocks worked in debug variant but not in release.
@drahovac do you have any clues as to why this is the case please?
fixes #89 
fixes #90

### CODE REVIEW

**Comment by RyanKoech** [comment]
Fixes #89

**Comment by drahovac** [comment]
The problem is in CrashReportingTree which is used in non debug build - 
 it crashes because of - TODO("Implement crashlytics"). So the part crashing was Timber.w(e.localizedMessage)
 
 Happens in every release timber call. Comment out TODO("Implement crashlytics") to stop release crashes.

**Comment by RyanKoech** [comment]
Wow! You're right! Quite talented with these obscure bugs. It fixes other issues I found out too. Thanks a lot!

**Comment by RyanKoech** [comment]
Fixes #90

**Pull request merged**
