### PR TITLE
Testing-76 :: Fix test build

### LINKED ISSUE #76: Testing: Fix failing tests
Fix the issue of unit tests not compiling and add an actions job to prevent future test failures.

### PR DESCRIPTION
**Pull request by drahovac**
Fixes https://github.com/RyanKoech/android-krypto/issues/76
Fix tests build. Add job for checking tests.
Failed test example: https://github.com/drahovac/android-krypto/pull/1/checks

### CODE REVIEW

**Comment by RyanKoech** [comment]
Great job. For the two usecases test, they should me moved into the coin list feature since there is where the usecases exists.

Also for running the tests, why not use `./gradlew test`? What is the difference?

Finally, for the commit messages, you can have them follow the format `<issue type>-<issue number> :: <commit-message>`. I'll update the contribution section. 

After that I think everything should be good to merge

**Comment by drahovac** [comment]
Moved  SaveDisplayCurrencyDataUseCaseTest to coin list feature (GetDisplayCurrencyDataUseCaseTest already moved).
Renamed commit messages.

 When running ./gradlew test it runs both testDebug and testRelease, so I was just saving actions time,
 but I guess it is not an issue in public project. Tested in fork - 
 gradle test - 3m 51s
 gradle testDebug - 2m 55s
 Just had problems with actions memory - had to add jvmargs property, but time difference is not that big, so we can run 
 gradlew test if you prefer (probably could catch some release build issues).

**Comment by RyanKoech** [comment]
Sure we can go ahead with `./gradlew test` and revert back to debug-only in case we need to.

**Comment by RyanKoech** [comment]
Awesome. Thanks!

**Pull request merged**
